[feat] #11 게시물 작성 관련 API 구현
Leets-Official/WeNeed-BE pull request #11
Opened 2024-01-10 07:35 UTC by anxi01

## 1. 무슨 이유로 코드를 변경했나요?
- 게시물 작성을 위한 api를 구현하였습니다.
- article/domain에서 폴더 구조를 article과 content로 나눴습니다.
- content는 image 타입과 paragraph 타입으로 나눴습니다.
- 썸네일과 본문에서의 이미지 첨부는 "/upload-image" 의 post를 이용하여 단편적으로 첨부할 수 있습니다. (jpg, png, jpeg만 첨부 가능)
- 다른 이외 파일(ppt, pdf...)들은 "/upload-file" 의 post를 이용하여 list로 묶어 첨부할 수 있습니다.
<br>
- 게시물 작성 과정은 다음과 같습니다.

1. 썸네일을 등록할 때 "/upload-image" 의 post를 이용하여 업로드합니다. 이때 반환하는 url을 request에 넣습니다.
2. content(본문)에서는 text 혹은 image를 넣을 수 있습니다. 순서는 id를 통해 프론트에서 받아옵니다. 여기서 image 또한 썸네일과 동일한 과정을 거칩니다.
3. 이외 첨부 파일들은 "/upload-file" 의 post를 이용하여 여러개 업로드할 수 있습니다. 이때 반환하는 url 리스트를 files request에 넣습니다. 
4. 포트폴리오일 경우, 팀원을 검색하는 api를 이용하여 userId를 가져와 요청 값에 넣습니다. 그러면 UserArticle에 해당 articleId에 게시물 작성자와 더불어 팀원들이 추가됩니다. 

<br>

## 2. 어떤 위험이나 장애를 발견했나요?
<br>

## 3. 관련 스크린샷을 첨부해주세요.
<img width="660" alt="스크린샷 2024-01-10 오후 4 30 57" src="https://github.com/Leets-Official/WeNeed-BE/assets/123073840/42153555-962e-4ecd-8208-424ca0e0a47c">
<img width="660" alt="스크린샷 2024-01-10 오후 4 32 31" src="https://github.com/Leets-Official/WeNeed-BE/assets/123073840/192fbcba-187d-4dd6-9545-11c878ee5a4d">
<img width="464" alt="스크린샷 2024-01-10 오후 4 32 50" src="https://github.com/Leets-Official/WeNeed-BE/assets/123073840/52ab2fe1-e297-4ff0-9af1-a964e0fd27f5">

<br>

## 4. 완료 사항
- 게시물 작성 및 팀원 조회 API 구현
<br>

## 5. 추가 사항
- 현재 로그인한 사용자의 정보를 받아들일 수 없어 가짜 유저를 생성하여 테스트하였습니다. -> 로그인 구현시 수정 필요
- 포트폴리오 게시물 작성 요청시 teamMembersId의 리스트는 빈 리스트라도 필수로 들어가야 합니다. (없음 nullpointerexception)
- 팀원모집 게시물 작성 요청에는 teamMembersId가 없습니다.
- 게시물 작성 request에 file은 List<File>이 아닌 List<String> 입니다. 이후 Entity로 변환될 때 파싱되어 파일 list로 저장됩니다.
- 게시물 상세 조회시 팀원을 반환할 때, 포트폴리오 작성자 또한 팀원에 같이 포함되는지 아닌지 정해야합니다.
- 파일 개당, 총합 용량 크기를 정해야합니다.

close #10

2024-01-10 07:48 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/domain/content/ParagraphData.java
추후에 DBMS 메모리 부족시 Text 형식으로 변경도 고려하면 좋을 것 같습니다!

2024-01-10 08:02 UTC, jwnnoh requested changes

2024-01-10 08:02 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/dto/response/MemberInfoResponse.java
유저 id를 List<> 형식으로 가져오지 않는 이유가 있을까요?

2024-01-10 08:02 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/application/ArticleService.java
> +    return userRepository.findAllByNicknameStartingWith(nickname).stream()
id가 아닌 nickname을 통해 memberList를 가져오는 이유가 궁금합니다..!

2024-01-10 08:02 UTC, jwnnoh commented on src/main/resources/application-local.yaml
gitignore 또는 환경변수 처리 부탁드립니다!

2024-01-10 08:38 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/domain/content/ParagraphData.java
Text로 변경할지말지 고민했는데 변경하는게 좋겠네요!
감사합니다!

2024-01-10 08:46 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/dto/response/MemberInfoResponse.java
유저를 검색할 때 해당 유저마다 userId를 List<>로 controller에서 반환해서 그렇습니다!

2024-01-10 08:47 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/application/ArticleService.java
> +    return userRepository.findAllByNicknameStartingWith(nickname).stream()
팀원을 찾을 때 게시물 작성 페이지에서 팀원의 닉네임을 통해 찾기 때문입니다!

2024-01-10 08:54 UTC, jwnnoh approved these changes
고생하셨습니다..!

2024-01-10 11:12 UTC, jiixon requested changes
하나의 API에 많은 데이터를 저장해야하고, 외부저장소까지 이용해야해서 꼼꼼히 봐야할것 같아요!
S3에 업로드하는 Service 부분 코드 수정 확인 후 다시 리뷰 달겠습니다!

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/api/ArticleController.java
`@ ApiOperation`, `@Api` ,`@ ApiParam` 등 Swagger API를 사용하는 만큼 해당 컨트롤러에 대한 부가적인 설명을 붙이는 것이 어떨까요?

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/application/ArticleService.java
> +            .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 존재하지 않습니다."));
해당 오류를 클래스로 설정하여 다루는 것이 어떨까요? 사용자가 존재하지 않는 에러는 자주 쓰일수 있기에, UserNotFound exception을 만드는 것이 좋겠네요!

`domain/user/exception/UserNotFoundException` 클래스를 만들고, 만들어둔 `global/error/exception`을 extends 해오는 방식이 좋겠네요! 그리고 해당 에러에 부합하는 에러코드를 추가하면 좋을것 같습니다.

에러코드 작성 방법을 아래와 같습니다.
```
public class UserNotFoundException extends ServiceException {
    public UserNotFoundException(){
        super(ErrorCode.USER_NOT_FOUND);
    }
}
```

코드는 `.orElseThrow(() -> new UserNotFoundException());` 가 되겠네요!

2024-01-10 11:12 UTC, jiixon commented on src/main/resources/application-local.yaml
application-dev.yaml 파일도 올려주세요!

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/domain/content/ImageData.java
이미지를 따로 그안에 받는거면 해당 타입은 MultipartFile일것 같네요!

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/s3/api/S3Controller.java
s3 업로드는 하나의 API가 아닙니다! 서비스 계층에서 처리하도록 해주세요:)

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/s3/application/S3Service.java
> +      throw new IllegalArgumentException("PNG, JPEG, JPG 이미지 파일만 가능합니다.");
위의 언급한것 처럼 exception 클래스로 처리한다면 좀더 보기좋은 코드일것 같습니다:)

2024-01-10 11:12 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/dto/request/AddArticleRequest.java
> +  private String thumbnail;
thumbnail도 이미지이므로 s3 사용하셔야 할것 같아요!

2024-01-10 16:30 UTC, anxi01 commented on src/main/resources/application-local.yaml
추가하였습니다!

2024-01-10 17:20 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/application/ArticleService.java
> +            .orElseThrow(() -> new IllegalArgumentException("해당 사용자가 존재하지 않습니다."));
예외 처리 클래스 만들어서 처리했습니다! 좋은 리뷰 감사합니다!

2024-01-10 17:21 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/domain/content/ImageData.java
MultiPartFile 썸네일, List<MultiPartFile> 본문에 배치하는 이미지 리스트, List<MultiPartFile> 첨부할 파일 리스트로 받아오게 변경하였습니다!

2024-01-10 17:22 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/s3/api/S3Controller.java
게시물 서비스계층에서 주입받아 처리하게 수정했습니다! 감사합니다!

2024-01-10 17:22 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/s3/application/S3Service.java
> +      throw new IllegalArgumentException("PNG, JPEG, JPG 이미지 파일만 가능합니다.");
FileUploadErrorException와 InvalidImageFileException을 추가하였습니다!

2024-01-10 17:23 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/dto/request/AddArticleRequest.java
> +  private String thumbnail;
thumbnail은 따로 MultiPartFile로 받아오게 수정하였습니다!

2024-01-10 17:44 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/api/ArticleController.java
Swagger 적용 하였습니다!

2024-01-11 04:37 UTC, jiixon approved these changes

2024-01-11 06:10 UTC, merged