Feat/#8/jwt 토큰인증 구현
Leets-Official/WeNeed-BE pull request #12
Opened 2024-01-10 08:39 UTC by jwnnoh

## 1. 무슨 이유로 코드를 변경했나요?
- oauth2.0을 통한 구글 로그인을 구현합니다.
- 해당 방식을 통한 JWT 토큰 인증 및 발급 메서드를 구현하였습니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
close #8 
<br>

## 5. 추가 사항
- 추후 oauth2.0을 통한 소셜 로그인 로직을 추가할 예정입니다
- 쿠키를 도입할 예정입니다.

2024-01-10 09:02 UTC, anxi01 approved these changes

2024-01-10 09:02 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +                    .parseClaimsJws(token);
token의 expiration이 현재 시간보다 적을 때의 조건을 추가하면 어떨까요?
`claims.getExpiration.before(new Date())` 일 때 true가 되는 식으로요!

2024-01-10 09:29 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +                    .parseClaimsJws(token);
적용하였습니다!

> token의 expiration이 현재 시간보다 적을 때의 조건을 추가하면 어떨까요? `claims.getExpiration.before(new Date())` 일 때 true가 되는 식으로요!

2024-01-10 09:40 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +                    .parseClaimsJws(token);
최고예요! 수고하셨습니다!!

2024-01-10 12:32 UTC, jiixon requested changes

2024-01-10 12:32 UTC, jiixon commented on src/main/resources/application-local.yaml
> +    password: ENC(jyZNNshW4DfvjG9sSLZeIMMheMSCaWat)
해당 부분은 로컬db이기때문에 굳이 올리실 필요가 없습니다!
jwt 나 yaml에 필요한 부분이 있으면 본인 password는 지우시고 올리셔야해요! 
그리고 로컬에서 작업하실때는 본인만 보기때문에 암호화도 굳이 하지않으셔도됩니다!

아래 jwt처럼 공통부분만 암호화해서 올리시면 됩니다:)

2024-01-10 12:32 UTC, jiixon commented on src/main/resources/application-local.yaml
-dev.yaml 파일도 올려주세요!

2024-01-10 12:32 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/jwt/service/TokenService.java
> +        }
해당 오류를 클래스로 설정하여 다루는 것이 어떨까요? InvalidTokenException을 만드는 것이 좋겠네요!

global/config/jwt/exception/InvalidTokenException 클래스를 만들고, 만들어둔 global/error/exception을 extends 해오는 방식이 좋겠네요! 그리고 해당 에러에 부합하는 에러코드를 추가하면 좋을것 같습니다.

에러코드 작성 방법을 아래와 같습니다.

```
public class InvalidTokenException extends ServiceException {
    public InvalidTokenException() {
        super(ErrorCode.INVALID_TOKEN);
    }
}
```

코드는 `throw new InvalidTokenException();` 가 되겠네요!

2024-01-10 12:32 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +    }
토큰 유효성 검사 메서드에서, 토큰이 만료 되었다는 에러를 좀더 구체적으로 명시해줘야하지 않을까요? 해당 클래스도 만들어서 `ExpiredTokenException` 이런식으로 구현하면 어떨까 싶습니다!

2024-01-10 12:51 UTC, jiixon requested changes

2024-01-10 12:51 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/token/controller/TokenController.java
> +    public ResponseEntity<CreateAccessTokenResponse> createNewAccessToken
`@ ApiOperation`, `@Api` ,`@ ApiParam` 등 Swagger API를 사용하는 만큼 해당 컨트롤러에 대한 부가적인 설명을 붙이는 것이 어떨까요?

2024-01-10 12:51 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/user/service/UserService.java
> +    }
성민님께도 비슷한 에러가 있어 `UserNotFoundException`을 적용 시켜달라고 리뷰 달았습니다! 둘중 한분이서 먼저 클래스 만드시고 같이 사용하는게 좋을것 같네요!

2024-01-10 12:51 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
refreshToken을 생성하는 코드는어디에 있죠? 각각의 만료시간을 다르게 해야합니다! 

개발하신 api는 리프레쉬토큰 기반으로 액세스토큰을 새로 발급하는 것같아 보이는데 정확한 로직 설명 해주실수 있나요? 이 api를 언제 호출하는지, 그냥 발급만 하는 용도면 사용자가 계속해서 들어갈때마다 액세스토큰이 새로 발급되는건가요?

2024-01-10 14:09 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/token/controller/TokenController.java
> +    public ResponseEntity<CreateAccessTokenResponse> createNewAccessToken
> `@ ApiOperation`, `@Api` ,`@ ApiParam` 등 Swagger API를 사용하는 만큼 해당 컨트롤러에 대한 부가적인 설명을 붙이는 것이 어떨까요?

불필요한 api 및 dto 삭제하였습니다!

2024-01-10 15:14 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/user/service/UserService.java
> +    }
> 성민님께도 비슷한 에러가 있어 `UserNotFoundException`을 적용 시켜달라고 리뷰 달았습니다! 둘중 한분이서 먼저 클래스 만드시고 같이 사용하는게 좋을것 같네요!

해당 클래스 생성 후 적용하였습니다!

2024-01-10 15:15 UTC, jwnnoh commented on src/main/resources/application-local.yaml
> +    password: ENC(jyZNNshW4DfvjG9sSLZeIMMheMSCaWat)
gitignore 재적용하여 해결하였습니다!

2024-01-10 15:15 UTC, jwnnoh commented on src/main/resources/application-local.yaml
적용하였습니다!

2024-01-10 15:16 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/service/TokenService.java
> +        }
해당 클래스 적용 및 그에 맞는 에러코드 적용 후, Invalid와 Expired에 따른 에러 코드 메세지를 다르게 작성하였습니다!

2024-01-10 15:16 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +    }
마찬가지로 상세 클래서 구현 후 적용하였습니다!

2024-01-10 15:24 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
refreshToken의 생성 및 저장하는 로직을 추후 oauth 적용 시 쿠키를 통해 구현하려고 했습니다!
또한 refreshToken과 accessToken은 추후 상수 및 환경변수 설정을 통해 만료시간을 다르게 하여 적용하겠습니다.

전체적인 토큰 로직은 refreshToken을 통해 accessToken의 유효성을 검증, 재발급받는 로직입니다. accessToken의 유효성 검사를 통해 만약 만료되었을 경우 유효한 refreshToken을 통해 재발급받고, 만약 refreshToken이 만료되었을 경우, 두 토큰 모두 다 재발급 받는 로직을 이어서 구현할 예정입니다. 

따라서 로그인/로그아웃에 관한 전체적인 로직은 추후 oauth 로직을 작성하며 완성시킬 예정입니다!

2024-01-11 04:53 UTC, jiixon requested changes

2024-01-11 04:53 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/security/SecurityConfig.java
TokenAuthenticationFilter를 securityConfig 에 `addFilterBefore` 와 같이 필터등록해주셔야합니다!

2024-01-11 04:53 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +    }
만료된 에러가 났을때 리턴값으로 에러클래스에서 설정한 메시지와 에러코드를 확인하려는 용도로 따로 exception을 만들었는데, 

```
} catch (SignatureException | UnsupportedJwtException | IllegalArgumentException | MalformedJwtException e) {
            throw new InvalidTokenException(); //구축한 에러클래스
        } catch (ExpiredJwtException e) {
            throw new ExpiredTokenException(); //구축한 에러클래스
        }
```
이런식으로 처리해야하지않을까요?

2024-01-11 15:55 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +    }
해당 부분 적용하였고, `validToken` 메서드의 false값을 사용하는 로직 또한 수정 및 제거하였습니다!

2024-01-11 15:56 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/security/SecurityConfig.java
해당 부분 적용하였습니다. 꼼꼼하게 봐주셔서 감사합니다! 😄

2024-01-11 15:57 UTC, jiixon approved these changes

2024-01-11 15:58 UTC, merged