Feat/#17/구글 로그인 도입
Leets-Official/WeNeed-BE pull request #19
Opened 2024-01-13 17:38 UTC by jwnnoh

## 1. 무슨 이유로 코드를 변경했나요?
- oauth를 통한 구글 로그인 기능을 개발합니다.
<br>

## 2. 어떤 위험이나 장애를 발견했나요?

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항
- [ ] 리다이렉션을 통한 액세스 토큰을 가져옵니다.
- [ ] jwt를 통한 액세스 및 리프레시 토큰을 재발급할 수 있습니다.
<br>

## 5. 추가 사항
- [ ] 코드 리뷰를 통한 기능 개발의 완성이 필요합니다.
close #17

2024-01-15 14:50 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/config/oauth/OAUth2AUthorizationRequestBasedOnCookieRepository.java
> +public class OAUth2AUthorizationRequestBasedOnCookieRepository implements
클래스명 수정이 필요할 거 같아요!

2024-01-15 14:56 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/oauth/OAUth2AUthorizationRequestBasedOnCookieRepository.java
> +public class OAUth2AUthorizationRequestBasedOnCookieRepository implements
클래스명을 조금 더 명확하게 변경하면 괜찮을까요??

2024-01-15 15:03 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/config/oauth/OAUth2AUthorizationRequestBasedOnCookieRepository.java
> +public class OAUth2AUthorizationRequestBasedOnCookieRepository implements
`OAuth2AuthorizationRequestBasedOnCookieRepository` 이렇게 하시려던거 같은데 오타 난 거 같아요!

2024-01-16 14:57 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/oauth/OAUth2AUthorizationRequestBasedOnCookieRepository.java
> +public class OAUth2AUthorizationRequestBasedOnCookieRepository implements
수정하였습니다!

2024-01-16 19:44 UTC, jiixon requested changes

2024-01-16 19:44 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/user/service/UserService.java
> +    }
이부분도 전부 `UserNotFound`로 에러처리해도 좋을것 같습니다!

2024-01-17 18:03 UTC, anxi01 commented on src/main/java/org/example/weneedbe/global/config/oauth/dto/OAuthToken.java
> +    private String access_token;
이 클래스에선 스네이크 케이스를 사용하신 이유가 있을까요??

2024-01-17 19:15 UTC, jiixon approved these changes

2024-01-17 19:15 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/oauth/api/OAuthController.java
> +    }
accesstoken을 body에 담으면 되기때문에, 
`ResponseEntity.ok(new LoginResponse(accessToken));`
하면 되지않을까요?

그리고 LoginResponse에 tokenType은 왜 필요한거죠?

2024-01-17 19:15 UTC, jiixon commented on src/main/java/org/example/weneedbe/global/config/oauth/dto/LoginResponse.java
> +    }
프론트에게 accesstoken만 넘겨주면 되지않을까요?

2024-01-18 07:08 UTC, ay-eonii commented on src/main/java/org/example/weneedbe/global/config/jwt/service/RefreshTokenService.java
> +        refreshTokenRepository.save(refreshToken);
userId 로 찾은 `RefreshToken` 가 있으면 update 쿼리가 두 번 날아가지는 않나용?

2024-01-18 07:08 UTC, ay-eonii commented on src/main/java/org/example/weneedbe/domain/user/service/UserService.java
> +    }
이 부분 전에 쓰던 `@RequiredArgsConstructor` 사용하지 않은 이유가 있나요?

2024-01-18 07:08 UTC, ay-eonii commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +        String newRefreshToken = makeToken(new Date(now.getTime() + REFRESH_TOKEN_DURATION.toMillis()), user);
`makeToken()`에서 Date 객체 만들어서 사용하는데 Expiration 정하는 것도  `makeToken()`에서 처리하면 깔끔할 것 같아요

2024-01-18 11:44 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/oauth/dto/OAuthToken.java
> +    private String access_token;
DTO 자체를 전체 스네이크 케이스로 수정하였습니다!

2024-01-18 11:45 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/oauth/api/OAuthController.java
> +    }
해당 부분 수정하였습니다!

2024-01-18 11:46 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/oauth/dto/LoginResponse.java
> +    }
해당 부분 refeshToken까지 담아서 넣어주는 식으로  반영하였습니다!

2024-01-18 12:06 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/service/RefreshTokenService.java
> +        refreshTokenRepository.save(refreshToken);
해당 부분 수정하였습니다!

2024-01-18 12:06 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/user/service/UserService.java
> +    }
해당 부분 생성자 주입 코드를 따로 작성하는 식으로 진행하였습니다!

2024-01-18 12:06 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/global/config/jwt/TokenProvider.java
> +        String newRefreshToken = makeToken(new Date(now.getTime() + REFRESH_TOKEN_DURATION.toMillis()), user);
해당 부분 반영하여 변경하였습니다!

2024-01-18 12:06 UTC, merged