Feat/#15 메인페이지 조회 포트폴리오 api
Leets-Official/WeNeed-BE pull request #21
Opened 2024-01-14 11:27 UTC by jiixon

## 1. 무슨 이유로 코드를 변경했나요?
메인페이지 조회 포트폴리오 api를 작성하였습니다.

<br>

## 2. 어떤 위험이나 장애를 발견했나요?

1. `findPortfoliosByDetailTagsInOrderByCreatedAtDesc` jpql을 사용하려고 하였으나 오류가 발견되어, nativequery로 작성하였더니 오류가 해결되었습니다(현재는 jpql은 주석처리로 올렸습니다.)
2. RequestParam으로 `String[] detailTags` 와 방식으로 태그들을 받아야합니다. 하지만 게시물이 없을때는 null exception이 발생하여 이부분을 해결해야할것 같습니다.

<br>

## 3. 관련 스크린샷을 첨부해주세요.

<br>

## 4. 완료 사항

<br>

## 5. 추가 사항
close #15

2024-01-14 12:13 UTC, anxi01 requested changes
굉장히 고심하고 꼼꼼하게 작성하셨네요..!!
수고하셨습니다!

2024-01-14 12:13 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/api/MainController.java
> +            @ApiResponse(responseCode = "201"),
Get 요청이니 responseCode가 200이어야할 것 같습니다!

2024-01-14 12:13 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +                .title(article.getTitle())
분야는 어떻게 전해줘야할까요?

2024-01-14 12:13 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/dto/response/main/RecommendArticleDto.java
> +    private Boolean isBookmarked;
service에서는 boolean인데 둘중 하나로 통일하는 것이 어떨까요?

2024-01-14 12:23 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +                .title(article.getTitle())
프론트와 상의했을때, 핫게는 가중치알고리즘으로 계산했을때 1~5순위를 리스트로 주기로 헀습니다! 
분야는 필수적으로 필요하지 않다고 하여 필요한 데이터만 보내고 있습니다!

2024-01-14 12:24 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/dto/response/main/RecommendArticleDto.java
> +    private Boolean isBookmarked;
수정하였습니다!

2024-01-14 12:24 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/api/MainController.java
> +            @ApiResponse(responseCode = "201"),
수정하였습니다!

2024-01-14 14:39 UTC, anxi01 commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +                .title(article.getTitle())
아하 알겠습니다~

2024-01-14 14:44 UTC, anxi01 approved these changes
수고하셨습니다!

2024-01-14 16:12 UTC, jwnnoh requested changes
고민한 흔적이 정말 많이 느껴지는 코드입니다..!
고생 많으셨어요..!

2024-01-14 16:12 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        switch (sort) {
정렬 기준 문자열은 상수로 정의하여 사용하는 것이 어떨까요? 
오타 관리 및 추후 정렬 기준 변경 가능성에 대해 용이할 것 같습니다!

```Java
private final static String SORT_BY_RECENT = "최신순";
private final static String SORT_BY_HEARTS = "좋아요순";
private final static String SORT_BY_VIEWS = "조회수순";

2024-01-14 16:12 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        List<ArticleDto> articleList = articlesPage.getContent()
해당 부분 로직을 별도의 메서드로 분리하면 좋을 것 같습니다..!

```java
private List<ArticleDto> convertToArticleDtoList(List<Article> articles, User user) {
        return articles.stream()
                .map(article -> convertToArticleDto(article, user))
                .collect(Collectors.toList());
    }
```
이런 식으로 분리하면 `getMainArticleList` 내에서는

```java
List<ArticleDto> articleList = convertToArticleDtoList(articlesPage.getContent(), mockUser);
```

이런 식으로 가져올 수 있을 것 같습니다!

2024-01-14 17:10 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        switch (sort) {
좋습니다!!!! 수정하겠습니당

2024-01-14 17:27 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        List<ArticleDto> articleList = articlesPage.getContent()
넵!! 감사합니다! 수정하겠습니다:)

2024-01-14 19:09 UTC, jwnnoh reviewed
늦은 시간에 고생 많으십니다..!!

2024-01-14 19:09 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/domain/Article.java
> +    @Column(name = "thumb_nail", nullable = false)
thumbnail은 단일어인데, snakecase를 적용해야할 이유가 있을까요?

2024-01-14 19:09 UTC, jwnnoh commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        double bookmarkCountWeight = 0.5 * bookmarkRepository.countByArticle(article);
조회수는 요청 자체만으로도 카운트가 되니, 정말 죄송하지만 북마크의 가중치를 조회수보다 높이는 것은 어떻게 생각하시나요..?

2024-01-14 19:20 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/application/MainService.java
> +        double bookmarkCountWeight = 0.5 * bookmarkRepository.countByArticle(article);
좋은 의견인것 같습니다!! 좋아요(1.0) > 북마크(0.7) > 조회수(0.5)로 수정하겠습니다!

2024-01-14 19:20 UTC, jiixon commented on src/main/java/org/example/weneedbe/domain/article/domain/Article.java
> +    @Column(name = "thumb_nail", nullable = false)
엇 오타인것 같습니다! 수정하겠습니다~

2024-01-15 04:32 UTC, jwnnoh approved these changes
고생하셨습니다!!

2024-01-15 11:55 UTC, merged